[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  YARN_VERSION = "1.6.0"

[context.deploy-preview]
  command = "yarn build-preview"

[[redirects]]
  from = "/extranet"
  to = "/extranet/"

[[redirects]]
  from = "/admin"
  to = "/extranet/"
